# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba61037149a796dd5a11e1d6b9b1e4338e9272e060c8bfcce2a63433b4fb2e5abcaa5dcd6499dfff51c4b81100abd93f37fae49d9c0f077c4efbbb94f626175f

test:
  secret_key_base: ed0468015672f42ecaab6b1b5dcb8a0717553cc1cec9fb42d8fc1a5a11e1630b0113e6a30ee3317f802558541c11d69a4add8a7d313652e178e4412eee3d9775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
